# Generated by Django 2.0 on 2019-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=150, null=True)),
                ('mj', models.FloatField(blank=True, max_length=50, null=True)),
                ('high', models.FloatField(blank=True, max_length=50, null=True)),
                ('crown', models.FloatField(blank=True, db_column='Crown', max_length=50, null=True)),
                ('dj', models.FloatField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_fromweb',
                'managed': False,
            },
        ),
    ]
