# Generated by Django 2.0 on 2019-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seedtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('xingtai', models.CharField(max_length=15)),
                ('level', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
                ('high', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.FloatField()),
                ('time', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'seedtable',
                'managed': False,
            },
        ),
    ]
